; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[env]
build_flags = 
	-std=gnu++17
	-Wall
	-DFW_VERSION=\"0.2.0-dev\"
build_unflags = -std=gnu++11

[env:esp32dev]
platform = espressif32 @ ^6.9.0
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = partitions.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 921600
build_flags = 
	${env.build_flags}
	-DCORE_DEBUG_LEVEL=1
	-DCONFIG_ASYNC_TCP_RUNNING_CORE=1
	-DCONFIG_ASYNC_TCP_STACK_SIZE=8192
lib_deps = 
	bblanchon/ArduinoJson @ ^7.3.0
	knolleary/PubSubClient @ ^2.8
	ESP32Async/ESPAsyncWebServer @ ^3.7.0
	ESP32Async/AsyncTCP @ ^3.3.0
	plerup/EspSoftwareSerial @ ^8.2.0
	mlesniew/PicoMQTT@^1.1.1

[env:native]
platform = native
test_framework = unity
build_flags = 
	${env.build_flags}
	-DNATIVE_TEST
